name: 'hello-world'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo 'hellow-world1'
      
      - name: step2
        run: echo 'hellow-world2'
